#!/bin/sh

#get directory to cd to
fzfcdhome () {
  export FZF_DEFAULT_COMMAND="fd -H . $HOME"
  dir="$(fzf-tmux)"
  filetype="$(file "$dir" | awk '{print $2}')" #check if its a directory

  # cd to dir
  if [ "$filetype" = "directory" ]; then
    cd "$dir" || return
  else
    cd "$(dirname "$dir")" || return
  fi
}

fzfcdroot () {
  export FZF_DEFAULT_COMMAND="fd -H . /"
  dir="$(fzf-tmux)"
  filetype="$(file "$dir" | awk '{print $2}')" #check if its a directory
  
  # cd to dir
  if [ "$filetype" = "directory" ]; then
    cd "$dir" || return
  else
    cd "$(dirname "$dir")" || return
  fi
}

#create scripts and edit 'em
scripter () {
  script="$PWD/$1"
  exists="$(/bin/ls -A | /bin/grep "$1")"
  
  if [ "$exists" = "$1" ]
  then
    "$EDITOR" "$script"
  else
    /bin/echo "#!/bin/sh" >> "$script"
    /bin/touch "$script"
    /bin/chmod +x "$script"
    "$EDITOR" "$script"
  fi
}

#copypath with fzf
fzfcppath () {
  export FZF_DEFAULT_COMMAND="fd -H . /"
  fzf-tmux | xclip -selection clipboard
}

#move files with ending $2 from $1 to $3
mvsubs() {
  find $1 -name "*.$2" -exec mv -it $3 {} +
}
