window:
  dimensions:
    columns: 100
    lines: 85

    decorations: buttonless
    opacity: 0.8

    font:
        normal:
    family: Terminess
    style: medium

    bold:
      family: Terminess
      style: bold

