[env]
TERM = "xterm-256color"

[font]
size = 14.0

[font.normal]
family = "BlexMono Nerd Font"
style = "Medium"

[window]
# columns = 0
dynamic_title = true
# lines = 0
opacity = 1
startup_mode = "Maximized"

[general]
import = ["/home/mt/.config/alacritty/theme.toml"]
