#!/bin/sh
#     _          _ _
# ___| |__   ___| | |
#/ __| '_ \ / _ \ | |
#\__ \ | | |  __/ | |
#|___/_| |_|\___|_|_|
#
#__   ____ _ _ __(_) __ _| |__ | | ___  ___
#\ \ / / _` | '__| |/ _` | '_ \| |/ _ \/ __|
# \ V / (_| | |  | | (_| | |_) | |  __/\__ \
#  \_/ \__,_|_|  |_|\__,_|_.__/|_|\___||___/

#export path
export PATH=$PATH:$HOME/.local/bin:$HOME/.local/appimage:$HOME/.local/pip:/usr/lib/cargo/bin/:/sbin
#XDG paths
export XDG_DATA_HOME=${XDG_DATA_HOME:="$HOME/.local/share"}
export XDG_CACHE_HOME=${XDG_CACHE_HOME:="$HOME/.cache"}
export XDG_CONFIG_HOME=${XDG_CONFIG_HOME:="$HOME/.config"}
export XDG_STATE_HOME=${XDG_STATE_HOME:="$HOME/.local/state"}
export GTK_MODULES=canberra:$GTK_MODULES

#clean ~
#export XAUTHORITY="$XDG_RUNTIME_DIR"/Xauthority #uncomment when no Display Manager
export ICEAUTHORITY="$XDG_CACHE_HOME"/ICEauthority
export ZDOTDIR=$HOME/.config/zsh
export PULSECOOKIE="$XDG_CONFIG_HOME"/pulse/cookie
export ASOUNDRC="$XDG_CONFIG_HOME"/alsa/asoundrc
export GNUPGHOME="$XDG_DATA_HOME"/gnupg
export GITCONFIG="$XDG_CONFIG_HOME"/git/config
export KDEHOME="$XDG_CONFIG_HOME"/kde
export _JAVA_OPTIONS=-Djava.util.prefs.userRoot="$XDG_CONFIG_HOME"/java
export CARGO_HOME="$XDG_DATA_HOME"/cargo
export GTK2_RC_FILES="$XDG_CONFIG_HOME"/gtk-2.0/gtkrc
export LESSHISTFILE=-
export GOPATH="${XDG_DATA_HOME:-$HOME/.local/share}/go"
export ANDROID_HOME="$XDG_DATA_HOME"/android
export ANDROID_VENDOR_KEYS="$XDG_DATA_HOME"/android/adbkeys
export NPM_CONFIG_USERCONFIG=$XDG_CONFIG_HOME/npm/npmrc

#programs
export FZF_DEFAULT_COMMAND="fd -H . $HOME"
export GTK_OVERLAY_SCROLLING=0 #gtk disable scrollbar disappearing
export BAT_THEME="gruvbox-dark"


#default apps
export EDITOR="nvim"
export VISUAL="$EDITOR"
export PAGER="batcat --color always --style plain"
export MANPAGER="sh -c 'sed -e s/.\\\\x08//g | bat -l man -p'"
export BROWSER="firefox"
