#!/bin/sh

#get directory to cd to
fzfcdhome () {
  export FZF_DEFAULT_COMMAND="fd -H . $HOME"
  dir="$(fzf-tmux)"
  filetype="$(file "$dir" | awk '{print $2}')" #check if its a directory

  # cd to dir
  if [ "$filetype" = "directory" ]; then
    cd "$dir" || return
  else
    cd "$(dirname "$dir")" || return
  fi
}

fzfcdroot () {
  export FZF_DEFAULT_COMMAND="fd -H . /"
  dir="$(fzf-tmux)"
  filetype="$(file "$dir" | awk '{print $2}')" #check if its a directory
  
  # cd to dir
  if [ "$filetype" = "directory" ]; then
    cd "$dir" || return
  else
    cd "$(dirname "$dir")" || return
  fi
}

#create scripts and edit 'em
scripter () {
  script="$PWD/$1"
  exists="$(/bin/ls -A | /bin/grep "$1")"
  
  if [ "$exists" = "$1" ]
  then
    "$EDITOR" "$script"
  else
    /bin/echo "#!/bin/sh" >> "$script"
    /bin/touch "$script"
    /bin/chmod +x "$script"
    "$EDITOR" "$script"
  fi
}

#copypath with fzf
fzfcppath () {
  export FZF_DEFAULT_COMMAND="fd -H . /"
  fzf-tmux | xclip -selection clipboard
}

#move files with ending $2 from $1 to $3
mvsubs() {
  find $1 -name "*.$2" -exec mv -it $3 {} +
}

#convert base 10 to binary
tobinary(){
    n=$(($1))
    bits=""
    sign=""
    if [ "$n" -lt 0 ]; then
        sign=- n=$((-n))
    fi
    while [ "$n" -gt 0 ]; do
        bits="$(( n&1 ))$bits";
        : $(( n >>= 1 ))
    done
    printf "%s\n" "$sign${bits:-0}"
}

#get unix time
unixtime() {
  while true; do date +%s | figlet; sleep 1; clear; done
}

#get unix time in binary
unixtimebinary() {
  while true; do tobinary $(date +%s) | figlet; sleep 1; clear; done
}

