#!/bin/sh

# get directory to cd to
fzycdhome () {
	file=$(fd -H . "$HOME" | fzy)
	cd "$file" 2> /dev/null || cd "$(dirname "$file")" || echo "NO PERMISSION"
}

fzycdroot () {
	file=$(fd -H . / | fzy)
	cd "$file" 2> /dev/null || cd "$(dirname "$file")" || echo "NO PERMISSION"
}

# cd and edit file
fzyedhome () {
	file=$(fd -H . "$HOME" | fzy)
	cd "$(dirname "$file")" && "$EDITOR" "$file" || cd "$file" || return
}

fzyman () {
	selection="$(apropos . | fzy)"
	kommando="$(echo "$selection" | awk '{print $1}')"
	kapitel="$(echo "$selection" | sed "s/[^0-9.]*//g")"
	man "$kapitel" "$kommando"
}

fzyhist () {
	# TODO: get command history to prompt without x11 server
	com="$(tac "$HISTFILE" | fzy)"
	xdotool type "$com"
}

#copypath with fzy
fzycppath () {
	fd -H . / | fzy | xclip -selection clipboard
}

#create scripts and edit 'em
scripter () {
	script="$PWD/$1"
	exists="$(/bin/ls -A | /bin/grep "$1")"

	if [ "$exists" = "$1" ]
	then
		"$EDITOR" "$script"
	else
		/bin/echo "#!/bin/sh" > "$script"
		/bin/chmod +x "$script"
		"$EDITOR" "$script"
	fi
}

#move files with ending $2 from $1 to $3
mvsubs() {
	find "$1" -name "*.$2" -exec mv -it "$3" {} +
}

#convert base 10 to binary
tobinary(){
	n=$(($1))
	bits=""
	sign=""
	if [ "$n" -lt 0 ]; then
		sign=- n=$((-n))
	fi
	while [ "$n" -gt 0 ]; do
		bits="$(( n&1 ))$bits";
		: $(( n >>= 1 ))
	done
	printf "%s\n" "$sign${bits:-0}"
}

#get unix time
unixtime() {
	while true; do date +%s | figlet; sleep 1; clear; done
}

#get unix time in binary
unixtimebinary() {
	while true; do tobinary "$(date +%s)" | figlet; sleep 1; clear; done
}

#convert to webm
towebm() {
	ffmpeg -i "$1" -c:v libvpx-vp9 -crf 30 -b:v 0 -b:a 128k -c:a libopus "$(echo "$1" | tr -d '.')".webm
}

# nvim startup
nvimspeed() {
	nvim --startuptime ~/.config/nvim/startup.log -c exit && tail -100 ~/.config/nvim/startup.log
}
